version: "3.3"

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_SUPER_USER_USERNAME}
      POSTGRES_PASSWORD: ${DB_SUPER_SECRET_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"

volumes:
  db_data: {}